name: Needs Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      example_output: ${{ steps.example_step.outputs.example_output }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a script
        id: example_step
        run: echo "example_output=Hello World" >> $GITHUB_ENV

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use output from build job
        run: echo "The output from the build job is ${{ needs.build.outputs.example_output }}"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy
        run: echo "Deploying the application"
